'use client';

import { useState } from 'react';

export default function TestPage() {
  const [selectedFile, setSelectedFile] = useState(null);
  const [testParams, setTestParams] = useState({
    role: '',
    experience: '',
    skills: ''
  });
  const [customAnswers, setCustomAnswers] = useState([]);
  const [resumeResult, setResumeResult] = useState(null);
  const [questionsResult, setQuestionsResult] = useState(null);
  const [evaluationResult, setEvaluationResult] = useState(null);
  const [answersResult, setAnswersResult] = useState(null);
  const [loading, setLoading] = useState({});
  const [error, setError] = useState({});

  const handleFileChange = (event) => {
    const file = event.target.files[0];
    if (file) {
      setSelectedFile({
        name: file.name,
        size: file.size,
        type: file.type,
        file: file
      });
    }
  };

  const testResumeParser = async () => {
    if (!selectedFile?.file) {
      setError({ ...error, resume: 'Please select a file first' });
      return;
    }

    setLoading({ ...loading, resume: true });
    setError({ ...error, resume: null });

    try {
      const formData = new FormData();
      formData.append('resume', selectedFile.file);

      const response = await fetch('/api/parse-resume', {
        method: 'POST',
        body: formData,
      });

      const result = await response.json();
      
      if (response.ok) {
        setResumeResult(result);
      } else {
        setError({ ...error, resume: result.error || 'Failed to parse resume' });
      }
    } catch (err) {
      setError({ ...error, resume: 'Network error: ' + err.message });
    } finally {
      setLoading({ ...loading, resume: false });
    }
  };

  const testQuestionGenerator = async () => {
    if (!testParams.role || !testParams.experience || !testParams.skills || !testParams.skills.trim()) {
      setError({ ...error, questions: 'Please fill in all test parameters (role, experience, and skills)' });
      return;
    }

    setLoading({ ...loading, questions: true });
    setError({ ...error, questions: null });
    
    try {
      const response = await fetch('/api/generate-questions', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          ...testParams,
          skills: Array.isArray(testParams.skills) ? testParams.skills : testParams.skills.split(',').map(s => s.trim()).filter(s => s),
          skills: testParams.skills.split(',').map(s => s.trim()).filter(s => s)
        })
      });

      const result = await response.json();
      
      if (response.ok) {
        setQuestionsResult(result);
        // Initialize customAnswers for the generated questions
        setCustomAnswers(result.questions.map(() => ({ answer: '', timeTaken: 30 })));
      } else {
        setError({ ...error, questions: result.error || 'Failed to generate questions' });
      }
    } catch (err) {
      setError({ ...error, questions: 'Network error: ' + err.message });
    } finally {
      setLoading({ ...loading, questions: false });
    }
  };

  const testAnswerEvaluator = async () => {
    if (!questionsResult?.questions) {
      setError({ ...error, answers: 'Please generate questions first' });
      return;
    }

    setLoading({ ...loading, answers: true });
    setError({ ...error, answers: null });

    try {
      const response = await fetch('/api/evaluate-answers', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          questions: questionsResult.questions,
          answers: customAnswers.slice(0, questionsResult.questions.length)
        }),
      });

      const result = await response.json();
      
      if (response.ok) {
        setAnswersResult(result);
      } else {
        setError({ ...error, answers: result.error || 'Failed to evaluate answers' });
      }
    } catch (err) {
      setError({ ...error, answers: 'Network error: ' + err.message });
    } finally {
      setLoading({ ...loading, answers: false });
    }
  };

  return (
    <div className="min-h-screen bg-gray-50 p-8">
      <div className="max-w-6xl mx-auto">
        <header className="mb-8">
          <h1 className="text-3xl font-bold text-gray-900 mb-2">AI Interview Assistant - Live Testing</h1>
          <p className="text-gray-600">Test your deployed Gemini AI endpoints with real data. All responses are generated by AI.</p>
          <div className="mt-2 p-3 bg-blue-50 border border-blue-200 rounded">
            <p className="text-sm text-blue-800">
              <strong>🤖 Real AI Powered:</strong> This interface connects to your deployed Python FastAPI endpoints using Gemini 2.0 Flash Exp model. 
              Customize the inputs below to test with your own data.
            </p>
          </div>
        </header>

        <div className="grid lg:grid-cols-2 gap-8">
          {/* Resume Parser Test */}
          <div className="bg-white rounded-lg shadow-sm border p-6">
            <h2 className="text-xl font-semibold mb-4 text-blue-600">1. Resume Parser Test</h2>
            
            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Upload Resume (PDF/DOCX)
                </label>
                <input
                  type="file"
                  accept=".pdf,.docx"
                  onChange={handleFileChange}
                  className="block w-full text-sm text-gray-500 file:mr-4 file:py-2 file:px-4 file:rounded-full file:border-0 file:text-sm file:font-semibold file:bg-blue-50 file:text-blue-700 hover:file:bg-blue-100"
                />
              </div>

              <button
                onClick={testResumeParser}
                disabled={loading.resume || !selectedFile}
                className="w-full bg-blue-600 text-white px-4 py-2 rounded-md hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed"
              >
                {loading.resume ? 'Parsing...' : 'Parse Resume'}
              </button>

              {error.resume && (
                <div className="p-3 bg-red-100 border border-red-400 text-red-700 rounded">
                  {error.resume}
                </div>
              )}

              {resumeResult && (
                <div className="p-4 bg-green-50 border border-green-200 rounded">
                  <h3 className="font-semibold mb-2">Extracted Data:</h3>
                  <div className="space-y-1 text-sm">
                    <div><strong>Name:</strong> {resumeResult.name || 'Not found'}</div>
                    <div><strong>Email:</strong> {resumeResult.email || 'Not found'}</div>
                    <div><strong>Phone:</strong> {resumeResult.phone || 'Not found'}</div>
                  </div>
                </div>
              )}
            </div>
          </div>

          {/* Question Generator Test */}
          <div className="bg-white rounded-lg shadow-sm border p-6">
            <h2 className="text-xl font-semibold mb-4 text-green-600">2. Question Generator Test</h2>
            
            <div className="space-y-4">
              <div className="space-y-3">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Job Role</label>
                  <input
                    type="text"
                    value={testParams.role}
                    onChange={(e) => setTestParams({...testParams, role: e.target.value})}
                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-green-500"
                    placeholder="Full Stack Developer"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Experience Level</label>
                  <select
                    value={testParams.experience}
                    onChange={(e) => setTestParams({...testParams, experience: e.target.value})}
                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-green-500"
                  >
                    <option value="Entry-level">Entry-level</option>
                    <option value="Mid-level">Mid-level</option>
                    <option value="Senior">Senior</option>
                    <option value="Lead">Lead</option>
                  </select>
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Skills (comma-separated)</label>
                  <input
                    type="text"
                    value={testParams.skills}
                    onChange={(e) => setTestParams({...testParams, skills: e.target.value})}
                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-green-500"
                    placeholder="React, Node.js, JavaScript, MongoDB"
                  />
                </div>
              </div>

              <button
                onClick={testQuestionGenerator}
                disabled={loading.questions}
                className="w-full bg-green-600 text-white px-4 py-2 rounded-md hover:bg-green-700 disabled:opacity-50 disabled:cursor-not-allowed"
              >
                {loading.questions ? 'Generating...' : 'Generate Questions'}
              </button>

              {error.questions && (
                <div className="p-3 bg-red-100 border border-red-400 text-red-700 rounded">
                  {error.questions}
                </div>
              )}

              {questionsResult && (
                <div className="p-4 bg-green-50 border border-green-200 rounded max-h-60 overflow-y-auto">
                  <h3 className="font-semibold mb-2">Generated Questions:</h3>
                  <div className="space-y-2 text-sm">
                    {questionsResult.questions.map((q, index) => (
                      <div key={index} className="border-l-4 border-blue-400 pl-3">
                        <div className="font-medium">
                          Q{index + 1} ({q.difficulty}) - {q.timeLimit}s
                        </div>
                        <div className="text-gray-600">{q.question}</div>
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </div>
          </div>

          {/* Answer Evaluator Test */}
          <div className="bg-white rounded-lg shadow-sm border p-6 lg:col-span-2">
            <h2 className="text-xl font-semibold mb-4 text-purple-600">3. Answer Evaluator Test</h2>
            
            <div className="space-y-4">
              <div className="space-y-3">
                <label className="block text-sm font-medium text-gray-700">Custom Answers (edit to test your own responses):</label>
                {customAnswers.map((answerObj, index) => (
                  <div key={index} className="space-y-1">
                    <label className="block text-xs font-medium text-gray-500">Answer {index + 1}:</label>
                    <textarea
                      value={answerObj.answer}
                      onChange={(e) => {
                        const newAnswers = [...customAnswers];
                        newAnswers[index] = { ...newAnswers[index], answer: e.target.value };
                        setCustomAnswers(newAnswers);
                      }}
                      className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-purple-500 text-sm"
                      rows={2}
                    />
                    <div className="mt-1">
                      <label className="block text-xs text-gray-500 mb-1">Time taken (seconds):</label>
                      <input
                        type="number"
                        value={answerObj.timeTaken}
                        onChange={(e) => {
                          const newAnswers = [...customAnswers];
                          newAnswers[index] = { ...newAnswers[index], timeTaken: parseInt(e.target.value) || 0 };
                          setCustomAnswers(newAnswers);
                        }}
                        className="w-20 px-2 py-1 border border-gray-300 rounded text-xs"
                        min="0"
                      />
                    </div>
                  </div>
                ))}
              </div>

              <button
                onClick={testAnswerEvaluator}
                disabled={loading.answers || !questionsResult}
                className="w-full bg-purple-600 text-white px-4 py-2 rounded-md hover:bg-purple-700 disabled:opacity-50 disabled:cursor-not-allowed"
              >
                {loading.answers ? 'Evaluating...' : 'Evaluate Answers'}
              </button>

              {error.answers && (
                <div className="p-3 bg-red-100 border border-red-400 text-red-700 rounded">
                  {error.answers}
                </div>
              )}

              {answersResult && (
                <div className="p-4 bg-purple-50 border border-purple-200 rounded">
                  <h3 className="font-semibold mb-4">Evaluation Results:</h3>
                  
                  <div className="grid md:grid-cols-2 gap-4 mb-4">
                    <div className="bg-white p-3 rounded">
                      <div className="text-lg font-bold text-purple-600">
                        Overall Score: {answersResult.evaluation?.overallScore || 0}/10
                      </div>
                    </div>
                    <div className="bg-white p-3 rounded">
                      <div className="text-sm text-gray-600">
                        Recommendation: {answersResult.evaluation?.recommendation || 'N/A'}
                      </div>
                    </div>
                  </div>

                  <div className="space-y-3 max-h-60 overflow-y-auto">
                    {answersResult.evaluation?.individualScores?.map((eval_result, index) => (
                      <div key={index} className="bg-white p-3 rounded border">
                        <div className="flex justify-between items-start mb-2">
                          <div className="font-medium">Question {index + 1}</div>
                          <div className="text-sm font-bold text-purple-600">
                            {eval_result.score}/10
                          </div>
                        </div>
                        <div className="text-sm text-gray-600 mb-2">
                          {eval_result.feedback}
                        </div>
                        {eval_result.improvements && eval_result.improvements.length > 0 && (
                          <div className="text-xs text-blue-600">
                            💡 Suggestions: {eval_result.improvements.join(', ')}
                          </div>
                        )}
                      </div>
                    )) || []}
                  </div>

                  {answersResult.evaluation?.summary && (
                    <div className="mt-4 p-3 bg-white rounded border">
                      <h4 className="font-semibold mb-2">Summary:</h4>
                      <p className="text-sm text-gray-600">{answersResult.evaluation.summary}</p>
                    </div>
                  )}
                </div>
              )}
            </div>
          </div>
        </div>

        <div className="mt-8 p-4 bg-blue-50 rounded-lg">
          <h3 className="font-semibold mb-2">Testing Instructions:</h3>
          <ol className="text-sm text-gray-600 space-y-1">
            <li>1. First, upload a resume (PDF/DOCX) and test the parser</li>
            <li>2. Then generate questions for the interview</li>
            <li>3. Finally, evaluate the sample answers against the generated questions</li>
            <li>4. Check the browser&apos;s Network tab for detailed API responses</li>
          </ol>
        </div>
      </div>
    </div>
  );
}